/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DA1.main;

import DA1.event.EvenMenuSelected;
import DA1.from.DangNhap;
import DA1.from.From_1;
import DA1.from.From_2;
import DA1.from.From_3;
import DA1.from.From_4;
import DA1.from.From_5;
import DA1.from.From_6;
import DA1.from.From_7;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author Welcome
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        DA1.from.DangNhap dialog = new DangNhap(null, true);
//        dialog.setTitle("Đang Nhập Hệ Thống");
//        dialog.setResizable(false);
//        dialog.setLocationRelativeTo(null);
//        dialog.setVisible(true);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        menu1.initMoving(Main.this);
        menu1.addEventMenuSelected(new EvenMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0){
                    setFrom(new From_1());
                }else if(index == 1){
                    setFrom(new From_2());
                }
                else if(index == 2){
                    setFrom(new From_3());
                }
                else if(index == 3){
                    setFrom(new From_4());
                }
                else if(index == 4){
                    setFrom(new From_5());
                }
                else if(index == 5){
                    setFrom(new From_6());
                }
                else if(index == 6){
                    setFrom(new From_7());
                }
            }
        });
        setFrom(new From_1());
    }

    public Main(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void setFrom(JComponent com){
        MainPanel.removeAll();
        MainPanel.add(com);
        MainPanel.repaint();
        MainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new DA1.component.Menu();
        MainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        MainPanel.add(jPanel2, java.awt.BorderLayout.PAGE_END);
        MainPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1160, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private DA1.component.Menu menu1;
    // End of variables declaration//GEN-END:variables

}
