/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JForm;

import DA1.from.From_3;
import DA1.main.Main;
import DA1.model.NhaSanXuat;
import DA1.model.XuatXu;
import DA1.service.NSXService;
import DA1.service.XuatXuService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namtr
 */
public class JFAddXuatXu extends javax.swing.JFrame {

    public static From_3 f3;
    DefaultTableModel tbl = new DefaultTableModel();
    ArrayList<XuatXu> listXX = new ArrayList<>();
    int rowselect;

    public JFAddXuatXu(From_3 aThis) {
        initComponents();
        f3 = aThis ;
        setLocationRelativeTo(null);
        JFXuatXu();
        FillToTableThuoTinh();
        FillToTableThungracThuoTinh();

    }

    public void JFXuatXu() {
        // Các cài đặt khác...

        // Đặt hành vi đóng cửa sổ
        setDefaultCloseOperation(Main.DISPOSE_ON_CLOSE);
    }

    public void FillToTableThuoTinh() {
        tbl = (DefaultTableModel) tblThuocTinh.getModel();
        tbl.setRowCount(0);
        listXX = XuatXuService.selectTblThuocTinh();
        for (XuatXu thuocTinh : listXX) {
            tbl.addRow(new Object[]{thuocTinh.getId(), thuocTinh.getTenXuatXu()});

        }
    }

    public void FillToTableThungracThuoTinh() {
        tbl = (DefaultTableModel) tblThungRacThuocTinh.getModel();
        tbl.setRowCount(0);
        listXX = XuatXuService.selectTblThungRacThuoTinh();
        for (XuatXu thuocTinh : listXX) {
            tbl.addRow(new Object[]{thuocTinh.getId(), thuocTinh.getTenXuatXu()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuocTinh = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThungRacThuocTinh = new javax.swing.JTable();
        btnKhoiPhuc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtThuocTinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên thuộc tính", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuocTinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThuocTinh);

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnThem)
                .addGap(26, 26, 26)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(25, 25, 25))
        );

        table2.addTab("Thuộc tính", jPanel2);

        tblThungRacThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên thuộc tính", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblThungRacThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThungRacThuocTinhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThungRacThuocTinh);

        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhoiPhucMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhoiPhuc)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnKhoiPhuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table2.addTab("Thùng rác", jPanel3);

        jLabel1.setText("Kích thước");

        txtThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThuocTinhActionPerformed(evt);
            }
        });

        jLabel2.setText("Thêm nhanh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuocTinhMouseClicked
        //        rowselect = tblThuocTinh.getSelectedRow();
        //        txtThuocTinh.setText(tblThuocTinh.getValueAt(rowselect, 1).toString());
    }//GEN-LAST:event_tblThuocTinhMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        String ThuocTinh = txtThuocTinh.getText();
        if (!ThuocTinh.isEmpty()) {
            JOptionPane.showMessageDialog(this, XuatXuService.add(ThuocTinh));
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
            f3.fillToComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "Không được đê trống");
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        rowselect = tblThuocTinh.getSelectedRow();
        tbl = (DefaultTableModel) tblThuocTinh.getModel();
        if (rowselect == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng nào");
        } else {
            int id = (int) tbl.getValueAt(rowselect, 0);
            String ten = txtThuocTinh.getText();
            if (ten == null || ten.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập dữ liệu muốn sửa vào");
            } else {
                XuatXu tt = new XuatXu(id, ten);
                XuatXuService.update(tt);
                FillToTableThuoTinh();
                FillToTableThungracThuoTinh();
                f3.fillToComboBox();
                JOptionPane.showMessageDialog(this, "Đã sửa thành công");
            }
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked

        // Xóa thuộc tính và đưa vào thùng rác
        boolean itemDeleted = false;
        tbl = (DefaultTableModel) tblThuocTinh.getModel();
        for (int i = 0; i < tbl.getRowCount(); i++) {
            Boolean checked = (Boolean) tbl.getValueAt(i, 2);
            if (checked != null && checked) {
                itemDeleted = true;
                Integer id = (Integer) tbl.getValueAt(i, 0);
                XuatXuService.DayVaoThungRac(id);
            }
        }
        if (itemDeleted) {
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
            f3.fillToComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng nào");

        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void tblThungRacThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThungRacThuocTinhMouseClicked
        //        rowselect = tblThungRacThuocTinh.getSelectedRow();
        //        txtThuocTinh.setText(tblThungRacThuocTinh.getValueAt(rowselect, 1).toString());
    }//GEN-LAST:event_tblThungRacThuocTinhMouseClicked

    private void btnKhoiPhucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoiPhucMouseClicked
        boolean itemSelected = false;
        tbl = (DefaultTableModel) tblThungRacThuocTinh.getModel();
        for (int i = 0; i < tbl.getRowCount(); i++) {
            Boolean checked = (Boolean) tbl.getValueAt(i, 2);
            if (checked != null && checked) {
                itemSelected = true;
                Integer id = (Integer) tbl.getValueAt(i, 0);
                XuatXuService.returnItem(id);
            }
        }
        if (itemSelected) {
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
            f3.fillToComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng nào");
        }
    }//GEN-LAST:event_btnKhoiPhucMouseClicked

    private void txtThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThuocTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThuocTinhActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFAddXuatXu().setVisible(true);
//
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane table2;
    private javax.swing.JTable tblThungRacThuocTinh;
    private javax.swing.JTable tblThuocTinh;
    private javax.swing.JTextField txtThuocTinh;
    // End of variables declaration//GEN-END:variables
}
