/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JForm;

import DA1.from.From_3;
import DA1.main.Main;
import DA1.model.SanPhamChiTiet;
import DA1.service.SPCTService;
import DA1.service.SanPhamService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JFThungRacSPCT extends javax.swing.JFrame {

    public static From_3 f3;
    DefaultTableModel tbl = new DefaultTableModel();
    int i = 1;

    /**
     * Creates new form JFThungRacSPCT
     */
    public JFThungRacSPCT(From_3 This) {
        f3 = This;
        initComponents();
        fillToTable();
        setDefaultCloseOperation(Main.DISPOSE_ON_CLOSE);
    }

    public void fillToTable() {
        ArrayList<SanPhamChiTiet> list = new ArrayList<>();
        tbl = (DefaultTableModel) tblThungRacSPCT.getModel();
        tbl.setRowCount(0);
        list = (ArrayList<SanPhamChiTiet>) SPCTService.selectAllThungRac();
        for (SanPhamChiTiet s : list) {
            tbl.addRow(new Object[]{i++, s.getID(), s.getTenSanPham(), s.getNXS(), s.getXuatXu(), s.getGiaBan(), s.getKichCo(), s.getMauSac(), s.getDangDan(), s.getSoLuong()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnKhoiPhucThungRac = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThungRacSPCT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnKhoiPhucThungRac.setText("Khôi phục");
        btnKhoiPhucThungRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucThungRacActionPerformed(evt);
            }
        });

        tblThungRacSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Tên sản phẩm", "Nhà xản xuất", "xuất xứ", "Giá bán", "Kích cơ", "Màu sắc", "Dáng đàn", "Số lượng"
            }
        ));
        tblThungRacSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThungRacSPCTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThungRacSPCT);

        jLabel1.setText("KHO LƯU TRỮ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(btnKhoiPhucThungRac)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoiPhucThungRac))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoiPhucThungRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucThungRacActionPerformed

        if (i == -1) {
            // Không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng khôi phục!");
        } else {
            int id = Integer.parseInt(tblThungRacSPCT.getValueAt(selectRow, 1).toString());
            System.out.println("id dòng được chọn là : " + id);
            if (id == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn đối tượng khôi phục!");
            } else {
                SPCTService.returnItem(id);
                f3.fillToTableSanPhamChiTiet();
                f3.fillToComboBox();
            }
        }
        fillToTable();
    }//GEN-LAST:event_btnKhoiPhucThungRacActionPerformed

    int selectRow;

    private void tblThungRacSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThungRacSPCTMouseClicked
        selectRow = tblThungRacSPCT.getSelectedRow();
        System.out.println("dòng đươc chọn là: " + selectRow);
    }//GEN-LAST:event_tblThungRacSPCTMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFThungRacSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFThungRacSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFThungRacSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFThungRacSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFThungRacSPCT().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhucThungRac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblThungRacSPCT;
    // End of variables declaration//GEN-END:variables
}
